spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/{application}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/