server:
  port: 0

Warehouse:
  api:
    prefix: /api/v1/warehouse # Префикс url WarehouseController

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: dbuser
    password: 12345
    url: jdbc:postgresql://localhost:6545/warehouse
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
  sql:
    init:
      mode: always