grpc:
  server:
    port: 59092
  client:
    hub-router:
      address: 'discovery:///hub-router'

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/