aggregator:
  kafka:
    consumer:
      bootstrap.servers: localhost:9092
      group.id: sensor-aggregator
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: ru.yandex.practicum.aggregator.deserializer.SensorEventDeserializer
      auto.offset.reset: earliest

    producer:
      bootstrap.servers: localhost:9092
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: ru.yandex.practicum.aggregator.serializer.GeneralAvroSerializer