aggregator:
  kafka:
    config:
      bootstrap-servers: "localhost:9092"
      producer-client-id-config: "producer-2"
      producer-key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      producer-value-serializer: "ru.yandex.practicum.avro.AvroSerializer"
      consumer-group-id: "aggregator-group"
      consumer-client-id-config: "consumer-1"
      consumer-key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      consumer-value-deserializer: "ru.yandex.practicum.avro.SensorEventDeserializer"
      consume-attempt-timeout: 1000
      consumer-auto-commit: false
      sensor-events-topic: "telemetry.sensors.v1"
      sensor-snapshots-topic: "telemetry.snapshots.v1"