server:
  port: 0

kafka:
  config:
    bootstrap-address: localhost:9092
    close-client-timeout-sec: 10
    hub-consumer:
      client-id: hub-consumer
      group-id: analyzer-hub-group
      topics:
        - telemetry.hubs.v1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.yandex.practicum.deserializer.HubEventDeserializer
      poll-timeout-sec: 5
      auto-commit-record-count: 10
    snapshot-consumer:
      client-id: snapshot-consumer
      group-id: analyzer-snapshot-group
      topics:
        - telemetry.snapshots.v1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.yandex.practicum.deserializer.SensorSnapshotDeserializer
      poll-timeout-sec: 5
      auto-commit-record-count: 10
grpc:
  client:
    hub-router:
      address: static://localhost:59090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: dbuser
    password: 12345
    url: jdbc:postgresql://localhost:6542/analyzer
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
  sql:
    init:
      mode: always
logging:
  level:
    root: INFO
    ru:
      yandex:
        practicum: DEBUG
    org:
      springframework: INFO