server:
  port: 0

ShoppingStore:
  api:
    prefix: /api/v1/shopping-store # Префикс url ShoppingStoreController

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: dbuser
    password: 12345
    url: jdbc:postgresql://localhost:6543/shopping_store
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
  sql:
    init:
      mode: always